name: CI Implementation

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    strategy:
      matrix:
        bun-version: ['1.2.5']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

  e2e-test:
    strategy:
      matrix:
        bun-version: ['1.2.5']

    runs-on: ubuntu-latest

    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run E2E tests
        run: bun run ci:e2e
